# Generated by Django 3.2.9 on 2021-11-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_alter_menuelements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuelements',
            name='image',
            field=models.ImageField(upload_to='../assets/img/'),
        ),
    ]
