# Generated by Django 3.2.9 on 2021-11-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_alter_menuelements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuelements',
            name='image',
            field=models.ImageField(upload_to='assets/'),
        ),
    ]
